const actions = {
  SET_STATE: 'blog/SET_STATE',
  CREATE_BLOG: 'blog/CREATE_BLOG',
  GET_BLOG: 'blog/GET_BLOG',
  CREATE_ERROR: 'blog/CREATE_ERROR',
  GET_LIST: 'blog/GET_LIST',
  GET_LIST_ERROR: 'blog/GET_LIST_ERROR',
  GET_BLOG_BY_ID: 'blog/GET_BLOG_BY_ID',
  GET_BLOG_BY_ID_ERROR: 'blog/GET_BLOG_BY_ID_ERROR',
  DELETE_BLOG_BY_ID: 'blog/DELETE_BLOG_BY_ID',
  UPDATE_BLOG: 'blog/UPDATE_BLOG',
}

export default actions
